import streamlit as st
import requests

# Cloud Run API URL
API_URL = "https://stuperml-api-service-ntyvbonqeq-ew.a.run.app/predict"
# local_test_API_URL = "http://127.0.0.1:8000/predict"    # for local testing

st.set_page_config(page_title="Student Performance AI", page_icon="🎓")

# ---------------------------------------------------------
# HEADER
# ---------------------------------------------------------
st.title("🎓 Student Performance Predictor")
st.markdown("""
This app uses a Machine Learning model deployed on **Google Cloud Run** to predict 
student performance based on specific study and digital habits.
""")

# ---------------------------------------------------------
# INPUT FORM
# ---------------------------------------------------------
with st.form("prediction_form"):
    st.subheader("1. Academic Profile")

    # Grade Level (Mapped from the OHE features: 10th, 11th, 12th, 1st Year, etc.)
    grade_level = st.selectbox("Grade Level", ["10th", "11th", "12th", "1st Year", "2nd Year", "3rd Year"])

    col1, col2 = st.columns(2)
    with col1:
        study_hours = st.slider("Daily Study Hours", 0.0, 16.0, 5.0, step=0.5)
        attendance = st.slider("Attendance (%)", 0, 100, 90)
    with col2:
        sleep_hours = st.slider("Sleep Hours", 0.0, 12.0, 7.0, step=0.5)

    st.subheader("2. Digital Habits")
    col3, col4 = st.columns(2)
    with col3:
        social_media = st.number_input("Social Media (Hours/Day)", 0.0, 10.0, 2.0, step=0.5)
    with col4:
        ai_time = st.number_input("AI Usage (Minutes/Day)", 0, 300, 45)

    # AI Content Percentage (0.0 to 1.0)
    ai_content_pct = (
        st.slider("AI Generated Content in Work (%)", 0, 100, 20, help="Percentage of submitted work generated by AI")
        / 100.0
    )

    # Submit Button
    submitted = st.form_submit_button("Predict Score")

# ---------------------------------------------------------
# LOGIC
# ---------------------------------------------------------
if submitted:
    # Construct payload with the required features
    payload = {
        "rows": [
            {
                "grade_level": grade_level,
                "study_hours_per_day": study_hours,
                "attendance_percentage": attendance,
                "sleep_hours": sleep_hours,
                "social_media_hours": social_media,
                "ai_usage_time_minutes": ai_time,
                "ai_generated_content_percentage": ai_content_pct,
            }
        ]
    }

    # Send Request to Cloud Run
    try:
        with st.spinner("Asking the AI model..."):
            response = requests.post(API_URL, json=payload)

        if response.status_code == 200:
            prediction = response.json()["predictions"][0]
            st.balloons()
            st.success(f"### Predicted Final Score: {prediction:.2f} / 100")

            # Simple feedback based on score
            if prediction > 85:
                st.write("🌟 Amazing! Keep up the good work!")
            elif prediction > 60:
                st.write("👍 Good job, but there is room for improvement.")
            else:
                st.write("⚠️ Warning: You might want to adjust your study habits.")
        else:
            st.error(f"Error {response.status_code}: {response.text}")

    except Exception as e:
        st.error(f"Connection Error: {e}")
